### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by jaumard** [node-xbmc/node-xbmc#11]
I'm trying to use this module but can't manage to make it working... 
```
var connection = new Xbmc.TCPConnection({
    host: 'localhost',
    port: 9090,
    verbose: true
  });

  var xbmcApi = new Xbmc.XbmcApi;
 
  xbmcApi.setConnection(connection);
 
  xbmcApi.on('connection:data', function()  { console.log('onData');  });
  xbmcApi.on('connection:open', function()  { console.log('onOpen');  });
  xbmcApi.on('connection:close', function() { console.log('onClose'); });
```

And the result was : 
```
mac:nodeTest jaumard$ node test.js 
onClose
/Users/jaumard/Sites/nodeTest/node_modules/xbmc/lib/TCPConnection.js:186
          throw new Error("JSON parse error: " + ex);
          ^

Error: JSON parse error: Error: Unexpected end
Line: 1
Column: 0
Char: 
    at Object.onerror (/Users/jaumard/Sites/nodeTest/node_modules/xbmc/lib/TCPConnection.js:186:17)
    at emit (/Users/jaumard/Sites/nodeTest/node_modules/xbmc/node_modules/clarinet/clarinet.js:285:37)
    at error (/Users/jaumard/Sites/nodeTest/node_modules/xbmc/node_modules/clarinet/clarinet.js:320:5)
    at end (/Users/jaumard/Sites/nodeTest/node_modules/xbmc/node_modules/clarinet/clarinet.js:326:7)
    at Object.write (/Users/jaumard/Sites/nodeTest/node_modules/xbmc/node_modules/clarinet/clarinet.js:341:32)
    at Object.CParser.close (/Users/jaumard/Sites/nodeTest/node_modules/xbmc/node_modules/clarinet/clarinet.js:148:42)
    at Connection.onClose (/Users/jaumard/Sites/nodeTest/node_modules/xbmc/lib/TCPConnection.js:162:26)
    at Socket.<anonymous> (/Users/jaumard/Sites/nodeTest/node_modules/xbmc/lib/TCPConnection.js:4:61)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

Remote control and web server are enabled under Kodi settings. I install a web interface that use web socket and it's working but not when I'm trying like this... I'm on mac with Kodi 15.2

Any idea?

**Comment by moul** [comment]
Hi @jaumard there are multiple TCP protocols possible, are you sure the 9090 is the JSON-RPC one ?
This library won't work with another protocol (i.e websocket).

Can you try to enable all the "remote protocols" and try out each ports until you find the good one ?

Also you can get more information by setting up the `DEBUG=1` environment variable, you should see detailed dataframes

**Comment by jaumard** [comment]
Hi @moul 

Thanks for your help I restart kodi to look settings and now it's working normally. I suppose I just have to restart after enable the "remote protocols". 

So no problem thanks a lot!

**Comment by moul** [comment]
Perfect :)
