### ISSUE TITLE
Trying to connect when XBMC is down

### ISSUE THREAD

**Issue by KenDodman** [node-xbmc/node-xbmc#16]
When trying to connect when the XBMC machine is down or not reachable I get this. 
Error, and onClose events fire, but cant find where to try catch this 

```
/node_modules/xbmc/lib/TCPConnection.js:186
          throw new Error("JSON parse error: " + ex);
          ^

Error: JSON parse error: Error: Unexpected end
Line: 1
Column: 0
Char:
    at Object.onerror (/media/pi/redsquare/Nodes/tornTV/node_modules/xbmc/lib/TCPConnection.js:186:17)
    at emit (/media/pi/redsquare/Nodes/tornTV/node_modules/xbmc/node_modules/clarinet/clarinet.js:285:37)
    at error (/media/pi/redsquare/Nodes/tornTV/node_modules/xbmc/node_modules/clarinet/clarinet.js:320:5)
    at end (/media/pi/redsquare/Nodes/tornTV/node_modules/xbmc/node_modules/clarinet/clarinet.js:326:7)
    at Object.write (/media/pi/redsquare/Nodes/tornTV/node_modules/xbmc/node_modules/clarinet/clarinet.js:341:32)
    at Object.CParser.close (/media/pi/redsquare/Nodes/tornTV/node_modules/xbmc/node_modules/clarinet/clarinet.js:148:42)
    at Connection.onClose (/media/pi/redsquare/Nodes/tornTV/node_modules/xbmc/lib/TCPConnection.js:162:26)
    at Socket.<anonymous> (/media/pi/redsquare/Nodes/tornTV/node_modules/xbmc/lib/TCPConnection.js:4:59)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
```

**Comment by moul** [comment]
Hi @KenDodman 

I just released a v0.8.0 version that replaces the current throw by a standard error publish (uniform with the rest of the library)

Thanks for your feedback !
